name: Build and Deploy WebGL

on: push

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - name: Deploy to GitHub Pages
        if: matrix.targetPlatform == 'WebGL'
        run: |
          # Configurar variables
          BUILD_DIR=build/WebGL
          GH_PAGES_BRANCH=gh-pages
          DEPLOY_DIR=$(mktemp -d)

          # Clonar el branch de GitHub Pages
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 --branch=$GH_PAGES_BRANCH https://github.com/${{ github.repository }} $DEPLOY_DIR || git init $DEPLOY_DIR

          # Copiar la build al branch de GitHub Pages
          rsync -av --delete $BUILD_DIR/ $DEPLOY_DIR/

          # Publicar en el branch gh-pages
          cd $DEPLOY_DIR
          git add .
          git commit -m "Deploy WebGL build from commit ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $GH_PAGES_BRANCH
